// apps/angular-shell/src/app/home/home.component.ts
/* eslint-disable @typescript-eslint/no-empty-function */
import { Component, OnInit } from '@angular/core';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'module-federation-web-components-home',
  templateUrl: './home.component.html'
})
export class HomeComponent implements OnInit {
  constructor() {}

  // eslint-disable-next-line @angular-eslint/no-empty-lifecycle-method
  ngOnInit(): void {}
}


<div class="module-content-header">
  <img src="https://raw.githubusercontent.com/adrianiskandar/ModuleFederationWebComponents/085f37fd04a3d058ae3bc332a2e68f9cd1698632/apps/angular-host/src/assets/angular-icon.svg" width="100px" alt="Angular Icon" />
  <h1>Angular Component</h1>
</div>
<div class="module-content">
  <h1>Welcome to micro frontends and the multiverse of frameworks!</h1>
  <p>
    This page is a simple Angular component, but we are about to see something special, Module Federation + Web
    Components! </p>

  <div class="home-icons">
    <img src="https://github.com/adrianiskandar/ModuleFederationWebComponents/blob/main/apps/angular-host/src/assets/wc-mod-fed.png?raw=true" width="50%" alt="Module Federation logo" />
  </div>
  <!-- <div class="home-icons">
    <img src="assets/modfed.jpg" width="50%" alt="Module Federation logo" />
    <h1 class="plus"> + </h1>
    <img src="assets/wc-logo.svg" width="50%" alt="web components logo" />
  </div> -->
</div>

// apps/react-app/src/app/home/home.tsx
/* eslint-disable-next-line */
export interface HomeProps {}

export function Home(props: HomeProps) {
  return (
    <div>
      <p>
        This page is a React component loading from a remote application
        encapsulated in a web component!
      </p>
      <div className="home-icons">
        <img
          src="assets/wc-react.png"
          width="50%"
          alt="Module Federation logo"
        />
      </div>{' '}
    </div>
  );
}

export default Home;
