// apps/angular-app/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'module-federation-web-components-home',
  templateUrl: './home.component.html',
})
export class HomeComponent implements OnInit {
  constructor() {}

  // eslint-disable-next-line @angular-eslint/no-empty-lifecycle-method
  ngOnInit(): void {}
}

<p>
  This page is an Angular component loading from a remote application
  encapsulated in a web component!
</p>

// apps/react-app/src/app/home/home.tsx
/* eslint-disable-next-line */
export interface HomeProps {}

export function Home(props: HomeProps) {
  return (
    <div>
      <p>
        This page is a React component loading from a remote application
        encapsulated in a web component!
      </p>
      <div className="home-icons">
        <img
          src="assets/wc-react.png"
          width="50%"
          alt="Module Federation logo"
        />
      </div>{' '}
    </div>
  );
}

export default Home;
